"""
core/tier_mapper.py — Section B logic from kale_data_hub.py (pure Python, no Streamlit).

Contains TIER_MAP, BUSINESS_TYPE_EXCLUDE, and get_tier().
"""

TIER_MAP = {
    "day spas": "1", "spa": "1", "construction": "1", "builders": "1",
    "general contractors": "1", "contractors": "1", "remodeling contractors": "1",
    "carpet cleaners": "1", "cleaning service": "1", "cleaners": "1",
    "residential cleaning": "1", "maid service": "1", "insurance agents": "1",
    "mortgage brokers": "1", "logistics": "Do not email", "fleet services": "Do not email",
    "appliance repair": "1", "drywall": "1", "electricians": "1", "flooring": "1",
    "flooring service": "1", "hardwood flooring": "1", "carpet installation": "1",
    "garage door repair": "1", "heating and cooling": "1", "hvac": "1",
    "heating": "1", "air conditioning": "1", "heat pump repair": "1",
    "bathroom contractors": "1", "kitchen remodeling": "1", "home security": "1",
    "security systems": "1", "alarm services": "1", "fire alarm systems": "1",
    "home automation": "1", "commercial cleaning": "Do not email", "handyman": "1",
    "office cleaning": "Do not email", "interior design": "1", "closet suppliers": "1",
    "lighting contractors": "1", "lighting stores": "1", "concrete contractors": "1",
    "stamped concrete": "1", "printed concrete": "1", "painters": "1",
    "house painters": "1", "paint contractors": "1", "pest control": "1",
    "exterminators": "1", "mold removal": "1", "plumbers": "1",
    "drain services": "1", "window installation": "1", "restorations": "1",
    "water damage repair": "1", "asbestos removal": "1", "deck builders": "1",
    "driveways": "1", "paving contractors": "1", "fence contractors": "1",
    "portable toilets": "Do not email", "fence suppliers": "1", "landscaping": "1",
    "lawn care": "1", "tree service": "1", "chiropractors": "1", "dentists": "1",
    "cosmetic dentist": "1", "dental implants": "1", "orthodontists": "1",
    "pediatricians": "1", "pharmacies": "1", "plastic surgeons": "1",
    "cosmetic surgery": "1", "dog grooming": "1", "pet salon": "1",
    "dog boarding": "1", "dog training": "1", "pet stores": "1",
    "veterinarians": "1", "pool builder": "1", "pool contractors": "1",
    "swimming pools": "1", "tile contractors": "1", "blinds stores": "1",
    "venetian blinds": "1", "blinds installation": "1", "door installation": "1",
    "roofing": "1", "gutter cleaning": "1", "guttering service": "1",
    "chimney cleaners": "1",
    "auto dealerships": "2", "electrical engineer": "Do not email",
    "car dealership": "2", "used car dealer": "2", "auto repair": "2",
    "auto body repair": "2", "mechanics": "2", "auto glass": "2",
    "brake services": "2", "auto detailing": "2", "car detailing": "2",
    "beauty salon": "2", "beauticians": "2", "salons": "2", "hair salon": "2",
    "hair salons": "2", "medical spas": "2", "architects": "2", "preschools": "2",
    "daycare": "2", "learning centers": "2", "tutoring centers": "2",
    "language schools": "2", "language classes": "2", "theater": "2",
    "accountants": "2", "bookkeeping": "2", "credit unions": "2",
    "financial planners": "2", "financial advisors": "2", "finance services": "2",
    "car insurance": "2", "gyms": "2", "health clubs": "2", "fitness": "2",
    "pilates": "2", "yoga studio": "2", "lawyers": "2", "attorneys": "2",
    "divorce attorney": "2", "estate planning attorney": "2", "family law": "2",
    "hotels": "2", "acupuncture": "2", "hypnotherapists": "2",
    "dermatologists": "2", "esthetician": "2", "hospitals": "2",
    "laser eye": "2", "lasik": "2", "vein clinic": "2",
    "land surveyors": "Do not email", "laser hair removal": "2",
    "coolsculpting": "2", "cryotherapy": "2", "dui lawyer": "Do not email",
    "immigration lawyer": "Do not email", "criminal defense attorneys": "Do not email",
    "ophthalmologist": "2", "optometrists": "2", "opticians": "2",
    "malpractice lawyers": "Do not email", "patent attorney": "Do not email",
    "personal injury attorneys": "Do not email", "personal injury lawyer": "Do not email",
    "solicitors": "Do not email", "abogado": "Do not email",
    "paralegal services": "Do not email", "notary": "Do not email",
    "psychologists": "2", "psychotherapists": "2",
    "marketing agency": "Do not email", "digital marketing": "Do not email",
    "digital agency": "Do not email", "seo companies": "Do not email",
    "advertising agency": "Do not email", "copywriters": "Do not email",
    "web design": "Do not email", "psychiatrists": "2",
    "orthopedic surgeries": "2", "podiatrists": "2", "junk removal": "2",
    "waste management": "2", "waste removal": "2", "photographers": "2",
    "wedding photographer": "2", "home inspections": "2", "home staging": "2",
    "moving company": "2", "house removals": "2", "realtors": "2",
    "real estate agents": "2", "real estate broker": "2",
    "real estate brokers": "2", "estate agents": "2", "estate planners": "2",
    "antique dealers": "2", "auto parts stores": "2", "tire shops": "2",
    "carpet stores": "2", "frame shops": "2", "garden center": "2",
    "nurseries": "2", "appliances": "2", "rehab": "Do not email",
    "addiction treatment center": "Do not email", "window tinting": "2",
    "furniture stores": "2", "rv dealers": "2",
    "auto wrecker": "3", "car wash": "3", "limo service": "3",
    "taxi services": "3", "barbers": "3", "massages": "3",
    "tanning salons": "3", "dry cleaners": "3", "laundry services": "3",
    "laundromat": "3", "dance studios": "3", "music school": "3",
    "teachers": "3", "culinary schools": "3", "bowling alley": "3",
    "escape rooms": "3", "gokarting": "3", "casinos": "3", "band hire": "3",
    "disc jockey": "3", "magicians": "3", "cinema": "3",
    "bouncy castle hire": "3", "charities": "Do not email",
    "adoption agency": "Do not email", "animal feed": "Do not email",
    "flight schools": "Do not email", "airport transfers": "Do not email",
    "wedding venues": "3", "business coach": "Do not email",
    "coaching services": "Do not email", "call centers": "Do not email",
    "commercial loans": "Do not email", "engineering": "Do not email",
    "event planners": "3", "party planners": "3", "consultant": "Do not email",
    "security guards": "Do not email", "private detectives": "Do not email",
    "birthday parties": "3", "wedding planners": "3", "tuxedo rental": "3",
    "check cashing": "3", "business insurance": "3", "loan officers": "3",
    "florists": "3", "crossfit": "3", "boxing club": "3",
    "personal trainers": "3", "tailers": "3", "heat pump dealers": "3",
    "home renovation": "3", "led signs": "3", "windscreen repair": "3",
    "land clearing": "3", "motels": "3", "psychic": "3",
    "hurricane shutters": "Do not email", "portable buildings": "Do not email",
    "apartment rental": "Do not email", "furnished apartments": "Do not email",
    "office rental": "Do not email", "coworking space": "Do not email",
    "coworking spaces": "Do not email", "fortune tellers": "3",
    "assisted living facilities": "3", "doctors": "3", "sleep clinics": "3",
    "pain management": "3", "property management": "Do not email",
    "property maintenance": "Do not email", "real estate investor": "Do not email",
    "appraisers": "Do not email", "hearing aid store": "3",
    "medical associations": "3", "laboratories": "3", "blood tests": "3",
    "paternity testing": "3", "nursing homes": "3", "retirement homes": "3",
    "marriage counseling": "3", "counselors": "3", "churches": "Do not email",
    "bars": "Do not email", "night clubs": "Do not email", "cardiologist": "3",
    "gastroenterology": "3", "food wholesaler": "Do not email",
    "gynecologist": "3", "chinese restaurants": "Do not email",
    "prosthodontist": "3", "urologists": "3", "regeneration medicine": "3",
    "therapists": "3", "physical therapists": "3", "speech therapists": "3",
    "fishing boat charters": "3", "takeaway restaurant": "Do not email",
    "sandwich bar": "Do not email", "food trucks": "Do not email",
    "videography": "3", "fire safety": "3", "network consultants": "3",
    "computer repair": "3", "data recovery service": "3", "phone repair": "3",
    "towing service": "Do not email", "piano movers": "3", "self storage": "3",
    "campsite": "3", "golf courses": "3", "pawn brokers": "Do not email",
    "catering services": "3", "catering supplies": "3", "restaurants": "3",
    "dispensary": "Do not email", "cbd": "Do not email",
    "indian restaurants": "3", "italian restaurants": "3",
    "mexican restaurants": "3", "pizzerias": "3", "sushi restaurants": "3",
    "thai restaurants": "3", "cash for gold": "Do not email",
    "vegan restaurants": "3", "electronics store": "Do not email",
    "computer store": "Do not email", "phone shops": "Do not email",
    "convenience store": "Do not email", "gas stations": "Do not email",
    "farm equipment stores": "Do not email", "cafes": "3", "coffee shop": "3",
    "juice bar": "3", "bakeries": "3", "perfume stores": "3",
    "beauty schools": "3", "breweries": "3", "diving supplies": "3",
    "fishing supplies": "3", "bookstores": "3", "clothing": "3",
    "womens clothing stores": "3", "mens clothing stores": "3",
    "childrens clothing stores": "3", "boutique": "3", "bridal shop": "3",
    "consignment stores": "3", "fabric shops": "3",
    "office furniture": "Do not email", "party supplies": "Do not email",
    "craft supplies": "3", "gift shops": "3", "grocery stores": "3",
    "supermarkets": "3", "health stores": "3", "supplements": "3",
    "hobby stores": "3", "gun stores": "Do not email",
    "gun safes": "Do not email", "gunsmiths": "Do not email",
    "skate shops": "Do not email", "fitness supplies": "Do not email",
    "tattoo studios": "Do not email", "body piercings studio": "Do not email",
    "tattoo removal": "Do not email", "bedding store": "3",
    "vape stores": "Do not email", "crane rental": "Do not email",
    "trailer rental": "Do not email", "truck rental": "Do not email",
    "locksmiths": "3", "wholesalers": "Do not email", "jewelers": "3",
    "watch repair": "3", "office supply stores": "3", "shops": "3",
    "shoe stores": "3", "sport shop": "3", "sports wear": "3",
    "bicycle store": "3", "camping stores": "3", "golf store": "3",
    "toy stores": "3", "martial arts": "3", "jiu jitsu": "3",
    "bus charter": "Do not email", "car rental": "Do not email",
    "tennis clubs": "3", "travel agencies": "3",
}

BUSINESS_TYPE_EXCLUDE = [
    "church", "non profit", "nonprofit", "non-profit",
    "retail", "community", "charity", "charities",
    "association", "foundation", "volunteer", "other",
]


def get_tier(keyword):
    """Return the tier ("1", "2", "3", "Do not email") for a keyword, or "Unknown"."""
    if not keyword:
        return "Unknown"
    return TIER_MAP.get(keyword.strip().lower(), "Unknown")
